//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgendamentoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgendamentoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.AgendamentoMensagem", typeof(AgendamentoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento alterado com sucesso..
        /// </summary>
        public static string Agendamento_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Agendamento_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O agendamento que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Agendamento_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Agendamento_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento cadastrado com sucesso..
        /// </summary>
        public static string Agendamento_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Agendamento_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento encontrado com sucesso..
        /// </summary>
        public static string Agendamento_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Agendamento_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento excluído com sucesso..
        /// </summary>
        public static string Agendamento_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Agendamento_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O agendamento que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Agendamento_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Agendamento_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O agendamento não pertence ao usuário autenticado..
        /// </summary>
        public static string Agendamento_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Agendamento_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período informado para é inválido. Verifique as datas informadas..
        /// </summary>
        public static string Agendamento_Procurar_Periodo_Invalido {
            get {
                return ResourceManager.GetString("Agendamento_Procurar_Periodo_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento(s) do usuário encontrado(s) com sucesso..
        /// </summary>
        public static string Agendamentos_Encontrados_Com_Sucesso {
            get {
                return ResourceManager.GetString("Agendamentos_Encontrados_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da primeira parcela do agendamento não pode ser menor que a data atual..
        /// </summary>
        public static string Data_Primeira_Parcela_Menor_Data_Atual {
            get {
                return ResourceManager.GetString("Data_Primeira_Parcela_Menor_Data_Atual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do agendamento informado ({0}) é inválido..
        /// </summary>
        public static string Id_Agendamento_Invalido {
            get {
                return ResourceManager.GetString("Id_Agendamento_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O agendamento de ID {0} não existe..
        /// </summary>
        public static string Id_Agendamento_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Agendamento_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do cartão de crédito do agendamento é inválido..
        /// </summary>
        public static string Id_Cartao_Credito_Invalido {
            get {
                return ResourceManager.GetString("Id_Cartao_Credito_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da categoria do agendamento é obrigatório e não foi informado..
        /// </summary>
        public static string Id_Categoria_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Id_Categoria_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta e o ID do cartão de crédito do agendamento, ambos foram informados. Informe apenas um..
        /// </summary>
        public static string Id_Conta_Id_Cartao_Credito_Informados {
            get {
                return ResourceManager.GetString("Id_Conta_Id_Cartao_Credito_Informados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta e o ID do cartão de crédito do agendamento não foi informado. Informe pelo menos um dos dois..
        /// </summary>
        public static string Id_Conta_Id_Cartao_Credito_Nao_Informados {
            get {
                return ResourceManager.GetString("Id_Conta_Id_Cartao_Credito_Nao_Informados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta do agendamento é inválido..
        /// </summary>
        public static string Id_Conta_Invalido {
            get {
                return ResourceManager.GetString("Id_Conta_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da pessoa do agendamento é inválido..
        /// </summary>
        public static string Id_Pessoa_Invalido {
            get {
                return ResourceManager.GetString("Id_Pessoa_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum agendamento do usuário foi encontrado..
        /// </summary>
        public static string Nenhum_Agendamento_Encontrado {
            get {
                return ResourceManager.GetString("Nenhum_Agendamento_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação do agendamento deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Observacao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de parcelas informada é inválida..
        /// </summary>
        public static string Quantidade_Parcelas_Inválida {
            get {
                return ResourceManager.GetString("Quantidade_Parcelas_Inválida", resourceCulture);
            }
        }
    }
}
