//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParcelaMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParcelaMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.ParcelaMensagem", typeof(ParcelaMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de lançamento da parcela não pode ser superior a data atual..
        /// </summary>
        public static string Data_Lancamento_Maior_Data_Corrente {
            get {
                return ResourceManager.GetString("Data_Lancamento_Maior_Data_Corrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do agendamento e o ID da fatura, ambos foram informados. Informe apenas um..
        /// </summary>
        public static string Id_Agendamento_Id_Fatura_Informados {
            get {
                return ResourceManager.GetString("Id_Agendamento_Id_Fatura_Informados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do agendamento e o ID da fatura da parcela não foi informado. Informe pelo menos um dos dois..
        /// </summary>
        public static string Id_Agendamento_Id_Fatura_Nao_Informados {
            get {
                return ResourceManager.GetString("Id_Agendamento_Id_Fatura_Nao_Informados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do agendamento da parcela informado ({0}) é inválido..
        /// </summary>
        public static string Id_Agendamento_Invalido {
            get {
                return ResourceManager.GetString("Id_Agendamento_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da categoria do lançamento da parcela ({0}) é inválido..
        /// </summary>
        public static string Id_Categoria_Lancar_Parcela_Invalido {
            get {
                return ResourceManager.GetString("Id_Categoria_Lancar_Parcela_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta onde o lançamento da parcela será cadastrado ({0}) é inválido..
        /// </summary>
        public static string Id_Conta_Lancar_Parcela_Invalido {
            get {
                return ResourceManager.GetString("Id_Conta_Lancar_Parcela_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da fatura da parcela informado ({0}) é inválido..
        /// </summary>
        public static string Id_Fatura_Invalido {
            get {
                return ResourceManager.GetString("Id_Fatura_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da parcela informado ({0}) é inválido..
        /// </summary>
        public static string Id_Parcela_Invalido {
            get {
                return ResourceManager.GetString("Id_Parcela_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parcela de ID {0} não existe..
        /// </summary>
        public static string Id_Parcela_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Parcela_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da pessoa do lançamento da parcela ({0}) é inválido..
        /// </summary>
        public static string Id_Pessoa_Lancar_Parcela_Invalido {
            get {
                return ResourceManager.GetString("Id_Pessoa_Lancar_Parcela_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do motivo do descarte da parcela deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Motivo_Descarte_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Motivo_Descarte_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação da parcela deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Observacao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela alterada com sucesso..
        /// </summary>
        public static string Parcela_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Parcela_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parcela que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Parcela_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Parcela_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela cadastrada com sucesso..
        /// </summary>
        public static string Parcela_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Parcela_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela descartada com sucesso..
        /// </summary>
        public static string Parcela_Descartada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Parcela_Descartada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela encontrada com sucesso..
        /// </summary>
        public static string Parcela_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Parcela_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela excluída com sucesso..
        /// </summary>
        public static string Parcela_Excluida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Parcela_Excluida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela lançada com sucesso..
        /// </summary>
        public static string Parcela_Lancada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Parcela_Lancada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parcela que se deseja lançar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Parcela_Lancar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Parcela_Lancar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período informado é inválido. Verifique as datas informadas..
        /// </summary>
        public static string Parcela_Procurar_Periodo_Invalido {
            get {
                return ResourceManager.GetString("Parcela_Procurar_Periodo_Invalido", resourceCulture);
            }
        }
    }
}
